worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid       /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/json;

    log_format main '$remote_addr - [$time_local] "$request" $status $body_bytes_sent '
                    '"$http_referer" rt=$request_time';

    access_log /var/log/nginx/access.log main;

    sendfile    on;
    keepalive_timeout 65;

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    server {
       listen 80;
       server_name _;

       location / {
           default_type application/json;
           return 200 '{"status":"ok","service":"devops-sandbox-nginx","message":"No environment at this path. Create one with make create"}';
       }
       include /etc/nginx/conf.d/*.conf;
   }

}
